FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir aiogram httpx python-dotenv prometheus-client

COPY bot/ ./bot/

WORKDIR /app/bot

CMD ["python", "bot.py"]

